ez_systems.multifile_upload.controller.rest.check_permission:
    methods: [GET]
    path: /multifileupload/v1/check-permission/{parentLocationId}
    requirements:
        parentLocationId: '\d+'
    defaults:
        _controller: ez_systems.multifile_upload.controller.rest:checkPermission
