parameters:
    ez_systems.multifile_upload.provider.content_type_mappings.class: EzSystems\MultiFileUploadBundle\ApplicationConfig\Providers\ContentTypeMappings

services:
    ez_systems.multifile_upload.provider.content_type_mappings:
        class: '%ez_systems.multifile_upload.provider.content_type_mappings.class%'
        arguments:
            - '%ez_systems.multifile_upload.location_mappings%'
            - '%ez_systems.multifile_upload.default_mappings%'
            - '%ez_systems.multifile_upload.fallback_content_type%'
            - '%ez_systems.multifile_upload.max_file_size%'
        tags:
            - { name: ezsystems.platformui.application_config_provider, key: 'multiFileUpload' }
